version: '3.8'

services:
  backend:
    container_name: node-backend
    build:
      context: .
      dockerfile: Dockerfile
    image: node-backend:latest
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - OVH_ACCESS_KEY=${OVH_ACCESS_KEY}
      - OVH_SECRET_KEY=${OVH_SECRET_KEY}
      - OVH_BUCKET_NAME=${OVH_BUCKET_NAME}
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    container_name: postgres-sql
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
