services:
  backend:
    container_name: node-backend
    build:
      context: .
      dockerfile: Dockerfile
    image: node-backend:latest
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:password@postgres-sql:5432/mydatabase
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    container_name: postgres-sql
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: